/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List this agent's orders */
        get: operations["listOrders"];
        put?: never;
        /**
         * Create a new card order
         * @description Creates a pending order and returns Casper mainnet native CSPR
         *     payment instructions by default. Set `payment_asset: mock_usdc_cep18`
         *     with `payer_public_key` to use the mockUSDC CEP-18 test-token rail.
         *
         *     For amounts above the policy approval threshold, returns 202 with
         *     `phase: awaiting_approval` instead of payment instructions.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get order details
         * @description Returns the current state of an order. When `phase` is `ready`,
         *     the `card` object contains the simulated virtual card details.
         */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Subscribe to live order phase updates
         * @description Server-Sent Events stream of phase transitions for a single order.
         *     The server sends an immediate event with the current phase, emits a
         *     new event every time the order changes, and closes the stream when
         *     the order reaches a terminal phase.
         */
        get: operations["streamOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{orderId}/verify-payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a Casper mainnet payment
         * @description Verifies the submitted deploy hash against the order's quoted
         *     recipient, amount, chain, and correlation data. CSPR orders verify
         *     native transfer ID; mockUSDC CEP-18 orders verify sender, package hash,
         *     entry point, recipient, and amount. On success, the backend fulfills
         *     exactly one simulated virtual card and returns the receipt plus the
         *     updated order.
         */
        post: operations["verifyCasperPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get this agent's spend summary and budget */
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dry-run policy check without creating an order */
        get: operations["checkPolicy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrderRequest: {
            /** @description Positive USD amount string from 0.01 to 10000.00 */
            amount_usdc: string;
            /**
             * @description Defaults to cspr_casper. mock_usdc_cep18 requires payer_public_key.
             * @enum {string}
             */
            payment_asset?: "cspr_casper" | "mock_usdc_cep18";
            /** @description Casper payer public key required for mock_usdc_cep18 orders. */
            payer_public_key?: string;
            /** Format: uri */
            webhook_url?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        PaymentInstructions: components["schemas"]["CasperCSPRPaymentInstructions"] | components["schemas"]["MockUsdcCep18PaymentInstructions"];
        CasperCSPRPaymentInstructions: {
            /** @enum {string} */
            type: "casper_cspr_transfer";
            /** @enum {string} */
            network: "mainnet";
            /** @enum {string} */
            chain_name: "casper";
            /** @description Casper treasury public key hex */
            recipient: string;
            /** Format: uuid */
            order_id: string;
            amount_usdc: string;
            amount_cspr: string;
            amount_motes: string;
            transfer_id: number;
            /** Format: date-time */
            expires_at: string;
        };
        MockUsdcCep18PaymentInstructions: {
            /** @enum {string} */
            type: "casper_cep18_transfer";
            /** @enum {string} */
            asset: "mockUSDC";
            /** @enum {integer} */
            decimals: 6;
            /** @enum {string} */
            network: "mainnet";
            /** @enum {string} */
            chain_name: "casper";
            /** @description CEP-18 package hash verified by the backend */
            contract_package_hash: string;
            contract_hash?: string | null;
            sender_public_key: string;
            recipient_public_key: string;
            /** Format: uuid */
            order_id: string;
            amount: string;
            amount_base_units: string;
            /** Format: date-time */
            expires_at: string;
            verify_url?: string | null;
        };
        VerifyCasperPaymentRequest: {
            deploy_hash: string;
            /** @description Required for mock_usdc_cep18; optional stricter verification for CSPR. */
            sender_public_key?: string;
        };
        Budget: {
            spent_usdc: string;
            in_flight_usdc: string;
            committed_usdc: string;
            limit_usdc?: string | null;
            remaining_usdc?: string | null;
        };
        CardDetails: {
            number: string;
            cvv: string;
            expiry: string;
            brand?: string | null;
        };
        OrderCreatedResponse: {
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            status: "pending_payment";
            /** @enum {string} */
            phase: "awaiting_payment";
            amount_usdc: string;
            payment: components["schemas"]["PaymentInstructions"];
            poll_url: string;
            budget: components["schemas"]["Budget"];
            sandbox?: boolean;
        };
        OrderAwaitingApprovalResponse: {
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            phase: "awaiting_approval";
            /** Format: uuid */
            approval_request_id: string;
            amount_usdc: string;
            message?: string;
            note?: string;
            /** Format: date-time */
            expires_at?: string;
        };
        /** @enum {string} */
        OrderPhase: "awaiting_approval" | "awaiting_payment" | "processing" | "ready" | "failed" | "refunded" | "rejected" | "expired";
        OrderListItem: {
            /** Format: uuid */
            id: string;
            status: string;
            amount_usdc: string;
            /** @enum {string} */
            payment_asset: "cspr_casper" | "mock_usdc_cep18";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        OrderStatus: {
            /** Format: uuid */
            order_id: string;
            status: string;
            phase: components["schemas"]["OrderPhase"];
            amount_usdc: string;
            /** @enum {string} */
            payment_asset?: "cspr_casper" | "mock_usdc_cep18";
            payment?: components["schemas"]["PaymentInstructions"];
            receipt?: components["schemas"]["CasperPaymentReceipt"];
            card?: components["schemas"]["CardDetails"];
            error?: string | null;
            note?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            approval_request_id?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CasperPaymentReceipt: components["schemas"]["CasperCSPRPaymentReceipt"] | components["schemas"]["MockUsdcReceipt"];
        CasperCSPRPaymentReceipt: {
            /** @enum {string} */
            type: "casper_cspr_receipt";
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            payment_asset: "cspr_casper";
            network: string;
            chain_name: string;
            deploy_hash: string;
            sender_public_key?: string | null;
            recipient?: string | null;
            transfer_id: number;
            amount_motes?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
            /** @enum {string} */
            card_mode: "mock";
        };
        MockUsdcReceipt: {
            /** @enum {string} */
            type: "casper_mock_usdc_receipt";
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            payment_asset: "mock_usdc_cep18";
            network: string;
            chain_name: string;
            deploy_hash: string;
            sender_public_key?: string | null;
            /** @enum {string} */
            asset: "mockUSDC";
            decimals: number;
            contract_package_hash?: string | null;
            contract_hash?: string | null;
            recipient_public_key?: string | null;
            recipient_account_hash?: string | null;
            amount_base_units?: string | null;
            /** Format: date-time */
            verified_at?: string | null;
            /** @enum {string} */
            card_mode: "mock";
        };
        VerifyCasperPaymentResponse: {
            /** @enum {boolean} */
            ok: true;
            note?: string;
            receipt: components["schemas"]["CasperPaymentReceipt"];
            order: components["schemas"]["OrderStatus"];
        };
        UsageSummary: {
            api_key_id: string;
            label?: string | null;
            budget: components["schemas"]["Budget"];
            orders: {
                total: number;
                delivered: number;
                failed: number;
                refunded: number;
                in_progress: number;
            };
        };
        PolicyCheckResult: {
            /** @enum {string} */
            decision: "approved" | "blocked" | "pending_approval";
            rule?: string | null;
            reason?: string | null;
        };
        ErrorResponse: {
            error: string;
            message?: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request body or parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Too many requests */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listOrders: {
        parameters: {
            query?: {
                status?: "pending_payment" | "ordering" | "awaiting_approval" | "delivered" | "failed" | "refunded" | "refund_pending" | "expired" | "rejected";
                limit?: number;
                offset?: number;
                since_created_at?: string;
                since_updated_at?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of order summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListItem"][];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                /** @description Same key plus same body returns the cached order response for 24 hours. */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description Order created, waiting for Casper payment */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderCreatedResponse"];
                };
            };
            /** @description Order requires owner approval before payment */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderAwaitingApprovalResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Idempotency-Key reused with a different body */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimited"];
            /** @description Fulfillment system temporarily unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderStatus"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    streamOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    verifyCasperPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCasperPaymentRequest"];
            };
        };
        responses: {
            /** @description Casper payment verified and order fulfilled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCasperPaymentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description Order or deploy hash cannot be claimed in the current state */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Order payment window expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Deploy found but failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Deploy not found yet or not executed yet */
            425: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Budget and order count summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummary"];
                };
            };
        };
    };
    checkPolicy: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Policy evaluation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyCheckResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
}
